# Generated by Django 3.1.1 on 2020-09-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personal_id', models.CharField(max_length=12)),
                ('apartment', models.CharField(max_length=100)),
                ('head_caretaker', models.CharField(max_length=100)),
                ('physical_con', models.TextField()),
                ('mental_con', models.TextField()),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('mood', models.CharField(max_length=200)),
                ('social_activity', models.CharField(max_length=200)),
                ('coffee', models.CharField(max_length=200)),
                ('breakfast', models.CharField(max_length=200)),
                ('eating_needs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elders.elder')),
            ],
        ),
    ]
